made some optimization

diff --git a/termux-x11/tmx b/termux-x11/tmx
--- a/termux-x11/tmx
+++ b/termux-x11/tmx
@@ -11,66 +11,66 @@ set_color() {
 }
 
 trap ctrl_c INT
+
 extra=""
 server_pid=""
+ROOT_MODE=$(id -u)
 
 check_server() {
-    if is_root; then
+    if [ "$ROOT_MODE" -eq 0 ]; then
         [ ! -z "$(pidof com.termux-x11)" ] && server_pid=$(pidof com.termux-x11)
     else
         [ ! -z "$(pgrep com.termux-x11)" ] && server_pid=$(pgrep com.termux-x11)
     fi
-    if [ ! -z $server_pid ]; then
-        printf "${RED}XServer is Already running at ${server_pid}"
-        echo
-        printf "${BLUE}To terminate XServer run this command \`kill $server_pid\`${RESET}";echo
+
+    if [ -n "$server_pid" ]; then
+        printf "${RED}XServer is already running at PID: ${server_pid}\n"
+        printf "${BLUE}To terminate, run: \`kill $server_pid\`${RESET}\n"
         exit 0
     else
-        echo "Other XServer Not running."
+        echo "No XServer instance running."
     fi
 }
 
 ctrl_c() {
     echo ""
-    if is_root; then
+    if [ "$ROOT_MODE" -eq 0 ]; then
         rm -rf ${TMPDIR}/.X*
-        printf "${REDB}Setting up SELinux to $(setenforce 1)$(getenforce)${RESET}"
-        echo
+        printf "${REDB}Setting SELinux to enforcing: $(setenforce 1) $(getenforce)${RESET}\n"
     else
-        printf "${RED}Killing pulseaudio$(pulseaudio -k 2>/dev/null)${RESET}"
-        echo
+        if pgrep pulseaudio >/dev/null; then
+            printf "${RED}Stopping pulseaudio...${RESET}\n"
+            pulseaudio -k
+        fi
     fi
-    printf "${GREEN}Leaving...${RESET}"
-    echo
+    printf "${GREEN}Exiting...${RESET}\n"
 }
 
 setup_audio() {
-    if ! command -v "pulseaudio" &>/dev/null; then
-        echo "pulseaudio not found"
-        echo "installing it now."
+    if ! command -v pulseaudio &>/dev/null; then
+        echo "Pulseaudio not found. Installing..."
         apt update && apt install pulseaudio -y
     fi
 }
 
 start_audio() {
     setup_audio
-    printf "${CYAN}Starting pulseaudio${RESET}"
-    echo
-    printf "${RED}Killing pulseaudio if running$(pulseaudio -k 2>/dev/null)${RESET}"
-    echo
+    if pgrep pulseaudio >/dev/null; then
+        printf "${RED}Stopping existing Pulseaudio...${RESET}\n"
+        pulseaudio -k
+    fi
+    printf "${CYAN}Starting Pulseaudio...${RESET}\n"
     pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 -D
 }
 
 usage() {
-    printf "${CYAN}Usage: $0 [OPTIONS]"
-    echo
+    printf "${CYAN}Usage: $0 [OPTIONS]\n"
     echo "Options:"
-    echo " -h or --help		Display this Help message."
-    echo " -d or --debug		Use this if want Verbose output."
-    echo " -s or --sound		Use this if want audio in Termux-X11. not work while in root"
-    echo " -x or --xserver	Use this if want to pass X Server Options"
-    printf " to use in root use 'su -c $PREFIX/bin/tmx' or 'su -c <path of tmx>'.${RESET}"
-    echo
+    echo " -h or --help       Display this Help message."
+    echo " -d or --debug      Enable verbose output."
+    echo " -s or --sound      Enable audio in Termux-X11 (not supported in root)."
+    echo " -x or --xserver    Pass X Server options."
+    printf " To use in root: 'su -c $PREFIX/bin/tmx' or 'su -c <path to script>'.${RESET}\n"
 }
 
 handle_options() {
@@ -78,14 +78,13 @@ handle_options() {
         case $1 in
         -h | --help)
             usage
-            return 1
+            exit 0
             ;;
         -s | --sound)
-            if ! is_root; then
+            if [ "$ROOT_MODE" -ne 0 ]; then
                 start_audio
             else
-                printf "${RED}root dont support pulseaudio.${RESET}"
-                echo
+                printf "${RED}Pulseaudio not supported in root.${RESET}\n"
             fi
             ;;
         -d | --debug)
@@ -102,65 +101,47 @@ handle_options() {
         -x | --xserver)
             shift
             extra="$1"
-            printf "X Server Options: ${CYAN}${extra}${RESET}"
-            echo
-            #shift
+            printf "X Server Options: ${CYAN}${extra}${RESET}\n"
             ;;
         *)
-            echo "$1 is not a recognized"
+            echo "$1 is not a recognized option."
             usage
-            return 1
+            exit 1
             ;;
         esac
         shift
     done
 }
 
-is_root() {
-    if [ "$(id -u)" = "0" ]; then return 0; else return 1; fi
-}
-
 setup() {
-    local PREFIX=/data/data/com.termux/files/usr
-    local x11repo="${PREFIX}/etc/apt/sources.list.d/x11.list"
+    local PREFIX="/data/data/com.termux/files/usr"
     local loader="${PREFIX}/libexec/termux-x11/loader.apk"
-    if [ ! -f $x11repo ]; then
-        echo "x11-repo is not enabled, enabling now."
-        apt update && apt install x11-repo -y
-    fi
-    if [ ! -f $loader ]; then
-        echo "termux-x11 not installed, installing now."
+
+    if ! command -v termux-x11 &>/dev/null; then
+        echo "Termux-X11 not found. Installing..."
         apt update && apt install termux-x11-* -y
     fi
+
     export CLASSPATH=$loader
     unset LD_LIBRARY_PATH LD_PRELOAD
     /system/bin/app_process -Xnoimage-dex2oat / --nice-name="com.termux-x11" com.termux.x11.Loader $extra
 }
 
 setup_root() {
-    ## set SeLinux to permissive so termux-x11 will work with root
-    local enforce="setenforce 1"
-    local permissive="setenforce 0"
-    local getenforce="getenforce"
+    printf "${REDB}SELinux is $(getenforce)${RESET}\n"
+    printf "${REDB}Setting SELinux to permissive: $(setenforce 0) $(getenforce)${RESET}\n"
 
-    printf "${REDB}SELinux is $($getenforce)${RESET}"
-    echo
-    printf "${REDB}Setting up SELinux to $($permissive)$($getenforce)${RESET}"
-    echo
-
-    ## set env.
     export CLASSPATH="$(/system/bin/pm path com.termux.x11 | cut -d: -f2)"
     /system/bin/app_process -Xnoimage-dex2oat / --nice-name="com.termux-x11" com.termux.x11.CmdEntryPoint $extra
 }
 
 startX11() {
-    printf "${GREEN}Starting Termux-x11${RESET}"
-    echo
-    printf "${REDB}Clearing old logcat$(logcat -c)${RESET}"
-    echo
-    if is_root; then
-        echo "Running Termux-X11 With ROOT"
-        $(logcat -c)
+    printf "${GREEN}Starting Termux-x11${RESET}\n"
+    printf "${REDB}Clearing old logcat: $(logcat -c)${RESET}\n"
+
+    if [ "$ROOT_MODE" -eq 0 ]; then
+        echo "Running Termux-X11 as ROOT"
+        logcat -c
         setup_root
     else
         echo "Running Termux-X11"
